# Generated by Django 5.1.1 on 2024-09-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valikvastus',
            name='vastus_tekst',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
